branches:
  only:
    - master

os: linux

dist: bionic

language: php

php:
  # PHP 8.0
  - "nightly"
  - "7.4"
  - "7.3"
  - "7.2"

cache:
  directories:
    - "${HOME}/.composer/cache"

env:
  - LARAVEL_VERSION="^6.0" COMPOSER_VERSION="^2.0"
  - LARAVEL_VERSION="^7.0" COMPOSER_VERSION="^2.0"
  - LARAVEL_VERSION="^8.0" COMPOSER_VERSION="^2.0"

jobs:
  fast_finish: true
  exclude:
    - php: "7.2"
      env: LARAVEL_VERSION="^8.0" COMPOSER_VERSION="^2.0"
  include:
    - name: "Static Analysis"
      php:
        - "7.4"
      env:
        - LARAVEL_VERSION="^7.0" COMPOSER_VERSION="^2.0"
      script:
        - composer test:types
        - export -f travis_retry
        # Run Larastan on Laravel and Lumen sample applications
        - tests/laravel-test.sh
    - name: "Check EditorConfig adherence"
      php:
        - "7.4"
      before_install: skip
      install:
        - npm install --no-package-lock eclint
      script:
        - npx eclint check

before_install:
  # Must run before any additional files are created
  - test "$(find . -type f -not -path "./.git/*" -perm /111)" == ./tests/laravel-test.sh
  # Install Composer version 2.0
  - composer self-update --preview

install:
  - composer validate --strict
  - travis_retry composer require "illuminate/contracts:${LARAVEL_VERSION}" --no-interaction --dev --no-update
  - travis_retry composer require "composer/composer:${COMPOSER_VERSION}" --no-interaction --no-update --no-interaction
  - composer update --ansi --no-interaction --prefer-dist

script:
  - composer test:unit
