name: "tests"

on:
  push:
    # Prevent duplicating jobs on PR-s from local branches
    branches:
      - "master"
  pull_request: null
  schedule:
    - cron: "0 0 * * *"

jobs:
  tests:
    strategy:
      fail-fast: true
      matrix:
        php: ["8.0", "8.1"]
        laravel: ["^9.0"]
        dependencies:
            - "lowest"
            - "highest"

    name: "P${{ matrix.php }} - L${{ matrix.laravel }} ${{ matrix.dependencies == 'highest' && '↑' || '↓' }}"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v2"

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
          extensions: "dom, curl, libxml, mbstring, zip, fileinfo"
          tools: "composer:v2"
          coverage: "none"

      - name: "Check Composer configuration"
        run: "composer validate --strict"

      - name: "Check file permissions"
        run: "test \"$(find . -type f -not -path './.git/*' -executable)\" == ./tests/laravel-test.sh"

      - name: "Install lowest dependencies from composer.json"
        if: "matrix.dependencies == 'lowest'"
        run: "composer update --with='illuminate/contracts:${{ matrix.laravel }}' --no-interaction --no-progress --prefer-lowest"

      - name: "Install highest dependencies from composer.json"
        if: "matrix.dependencies == 'highest'"
        run: "composer update --with='illuminate/contracts:${{ matrix.laravel }}' --no-interaction --no-progress"

      - name: "Execute static analysis"
        run: "composer run-script test:types"

      - name: "Execute unit tests"
        run: "composer run-script test:unit"

      - name: "Run Larastan on Laravel sample applications"
        run: "tests/laravel-test.sh"
